### ISSUE TITLE
Sondes measure BGA-PC in RFU or ug/L not density

### ISSUE THREAD

**Issue by SteveHansonODEQ** [DEQrmichie/odeqcdr#26] opened 2021-05-06 00:49 UTC
https://github.com/OR-Dept-Environmental-Quality/odeqcdr/blob/7c6c160c08c3ef8205e5a287b74287a487b002cc/R/valid_values.R#L17
This density thing should be deleted and replaced with the AWQMS continuous characteristic "Phycocyanin (probe relative fluorescence)"

**Comment by DEQrmichie** [comment] 2021-05-27 15:45
Hi Steve,

Can you send me a list of all the AWQMS approved characteristic names that would be relevant for continous data? I can add it into the list. The current list is mostly what was in the original template.

**Comment by SteveHansonODEQ** [comment] 2021-10-26 00:54
The contin_volmon_import.R function still has this issue line 55 param_transform function is applying the "Algae, blue-green (phylum cyanophyta) density" to "bga"

From: HANSON Steve * DEQ 
Sent: Friday, May 28, 2021 8:42 AM
To: MICHIE Ryan * DEQ <ryan.michie@deq.state.or.us>
Cc: ROCKWELL Sarah * DEQ <sarah.rockwell@deq.state.or.us>
Subject: RE: [OR-Dept-Environmental-Quality/odeqcdr] Sondes measure BGA-PC in RFU or ug/L not density (#26)

Ryan, 
The list below is cut and pasted from the available characteristic names for building an import configuration.  It is, in my opinion, an awful list with lots of parameters in duplicate, non-specific, or just ones I question anyone really actually measures continuously. Sarah Rockwell has helped me with this list in the past and I always check with her before proceeding with this stuff. 

AWQMS Continuous Characteristic Names	DEQ possible	Sjh Comment
% undercut bank	?	doesn't seem real continuous param
Barometric pressure	Current	loaded with air or water
Bromide	?	
Calcium	?	
Chloride	?	
Chlorophyll a (probe relative fluorescence)	Current	
Chlorophyll a (probe)	ok	not specific
Chlorophyll a (probe) concentration, Chlorophyte (green algae)	Possible	current probe, ug/L unit
Chlorophyll a (probe) concentration, Cryptophyta (cryptophytes)	?	
Chlorophyll a (probe) concentration, Cyanobacteria (bluegreen)	Possible	current probe, ug/L unit
Chlorophyll a (probe) concentration, Dinophyta (diatoms)	?	This seems unlikely, the probes measure relative chlorophyll
Chlorophyll a (probe) concentration, Xanthophyte (yellow algae)	?	
Conductivity	ok	not specific if raw or specific
Copper	?	
Density	?	
Depth	Current	
Depth, data-logger (non-ported)	Current	
Depth, data-logger (ported)	Current	
Dissolved oxygen (DO)	Current	
Dissolved oxygen saturation	Current	
Flow	Current	poor name, stream discharge?
Fluoride	?	
Iodide	?	
Lead	?	
Nitrate	Current	
Oxidation reduction potential (ORP)	Current	not sure but maybe
Partial Pressure CO2	?	
pH	Current	
Phycocyanin	ok	poor option
Phycocyanin (probe relative fluorescence)	Current	
Phycocyanin (probe)	ok	not specific
Relative humidity	Current	
Resistivity	Current	
Salinity	Current	
Specific conductance	Current	
Temperature, air	Current	
Temperature, dew point air	Current	
Temperature, water	Current	
Total dissolved solids	Current	
Turbidity	Current	
Water level (probe)	Current	
Water Pressure	Current

**Comment by DEQrmichie** [comment] 2021-10-27 16:47
Hi Steve,  

I want to make sure I understand what the problem is and the fix. I assume you want to use "Phycocyanin (probe relative fluorescence)"  to replace  "Algae", "bga", or "blue-green (phylum cyanophyta) density".

Correct?

**Comment by DEQrmichie** [comment] 2021-10-27 17:06
Also what are the result units for Phycocyanin (probe relative fluorescence)?

**Comment by SteveHansonODEQ** [comment] 2021-10-27 17:17
The ...import.R functions translate imjported characterisitc abbreviations to names that appear to be consistent with AWQMS continuous parameter list. Starting on line 55 of cont_volmon_import.R
  param_transform <- function(col){
    dplyr::case_when(grepl("date", tolower(col)) ~ "Activity.Start.Date",
                     grepl("time", tolower(col)) ~ "Activity.Start.Time",
                     grepl("temp", tolower(col)) ~ "Temperature, water",
                     grepl("dos", tolower(col)) ~ "Dissolved oxygen saturation",
                     grepl("do", tolower(col)) ~ "Dissolved oxygen (DO)",
                     grepl("ph", tolower(col)) ~ "pH",
                     grepl("turb", tolower(col)) ~ "Turbidity",
                     grepl("cond", tolower(col)) ~ "Conductivity",
                     tolower(col) == 'q_r' ~ 'Flow',
                     grepl("flow", tolower(col)) ~ "Flow",
                     **grepl("chl", tolower(col)) ~ "Chlorophyll a"**,
                     grepl("depth", tolower(col)) ~ "Depth",
                     **grepl("bga", tolower(col)) ~ "Algae, blue-green (phylum cyanophyta) density"**,
                     TRUE ~ col) 

I have corrected this table for my use in a function contin_tmdl_import.R 
param_transform <- function(col){
    dplyr::case_when(grepl("date", tolower(col)) ~ "Activity.Start.Date",
                     grepl("time", tolower(col)) ~ "Activity.Start.Time",
                     grepl("temp", tolower(col)) ~ "Temperature, water",
                     grepl("dos", tolower(col)) ~ "Dissolved oxygen saturation",
                     grepl("do", tolower(col)) ~ "Dissolved oxygen (DO)",
                     grepl("ph", tolower(col)) ~ "pH",
                     grepl("turb", tolower(col)) ~ "Turbidity",
                     grepl("cond", tolower(col)) ~ "Conductivity",
                     tolower(col) == 'q_r' ~ 'Flow',
                     grepl("flow", tolower(col)) ~ "Flow",
                     **grepl("rchl", tolower(col)) ~ "Chlorophyll a (probe relative fluorescence)",**
                     grepl("depth", tolower(col)) ~ "Depth",
                     **grepl("rbga", tolower(col)) ~ "Phycocyanin (probe relative fluorescence)",**
                     TRUE ~ col)

Note that we import the data as rchl and rbga to indicate these are the relative measurements. in units of RFU- relative fluorescence unit.

The original chl and bga translations have issues. "Chlorophyll a" is insufficiently precise description but I guess not definitively incorrect based on continuous methods I'm aware of. "Algae, blue-green (phylum cyanophyta) density" is to best of my knowledge of current technology wrong. 

Continuous sensors measure concentrations of chlorophyll either in a relative unit of RFU or as an approximated concentration in microg/L. Continuous sensors also measure the pigment phycocyanin as a surrogate for blue-greens and again report either in a relative unit of RFU or as a concentration in microg/L. For both chlorophyll and blue-green we report only in RFU's because, based even on the manufacturer's literature which is usually over optimistic about performance, the concentrations in microg/L depend on assumptions that vary significantly over time and space and need to be verified with regression assessments vs water samples.

To be fair, with sufficient field data on blue-green densities it may be possible to build a regression and translate the continuous data measuring phycocyanin to density, but that is not what is reported from continuous loggers as far as I'm aware.

**Comment by DEQrmichie** [comment] 2021-10-27 17:32
Thanks. You said we never "report" these characteristics in units of ug/L. Is that the same thing as we never collect the data using these units and include it that way in the continuous data template?  Asking because the DQL precision and accuracy values in the conqc currently only have RFU as a percent difference. Right now if we get any data measured in ug/L the script will break.

**Comment by SteveHansonODEQ** [comment] 2021-10-27 17:50
Technically, yes we do collect in both RFU and ug/L but the ug/L concentrations are not corrected or reported. I think the most robust approach would be to include, in addition to the rchl and rbga translations, a grepl for chl -> Chlorophyll a (probe) and bga -> Phycocyanin (probe). (yes I have included the generic names I don't like). I didn't include these chl and bga translation in my tmdl version b/c I know we aren't reporting these.

We don't have any QC criteria for these chl and bga to add to the conqc table.

**Comment by DEQrmichie** [comment] 2021-10-27 19:13
I think this has been fixed in 5084c30. You should download the updated version and confirm.

**Comment by SteveHansonODEQ** [comment] 2021-10-27 19:38
Yes Ryan. Sorry. I must have screwed up in my project set up. I downloaded the updated version but somewhere in my process it appears it pushed me to an older version.

**Closed as completed** 2022-01-19 23:59 UTC
